const ACTION_TYPES = {
    //get Superheroes
    GET_SUPERHEROES_ACTION: 'GET_SUPERHEROES_ACTION',
    GET_SUPERHEROES_REQUEST: 'GET_SUPERHEROES_REQUEST',
    GET_SUPERHEROES_SUCCESS: 'GET_SUPERHEROES_SUCCESS',
    GET_SUPERHEROES_ERROR: 'GET_SUPERHEROES_ERROR',
    //get Superhero by id
    GET_SUPERHERO_ACTION: 'GET_SUPERHERO_ACTION',
    GET_SUPERHERO_REQUEST: 'GET_SUPERHERO_REQUEST',
    GET_SUPERHERO_SUCCESS: 'GET_SUPERHERO_SUCCESS',
    GET_SUPERHERO_ERROR: 'GET_SUPERHERO_ERROR',
    //create new Superhero
    CREATE_SUPERHERO_ACTION: 'CREATE_SUPERHERO_ACTION',
    CREATE_SUPERHERO_REQUEST: 'CREATE_SUPERHERO_REQUEST',
    CREATE_SUPERHERO_SUCCESS: 'CREATE_SUPERHERO_SUCCESS',
    CREATE_SUPERHERO_ERROR: 'CREATE_SUPERHERO_ERROR',
    //delete Superhero   `
    DELETE_SUPERHERO_ACTION: 'DELETE_SUPERHERO_ACTION',
    DELETE_SUPERHERO_REQUEST: 'DELETE_SUPERHERO_REQUEST',
    DELETE_SUPERHERO_SUCCESS: 'DELETE_SUPERHERO_SUCCESS',
    DELETE_SUPERHERO_ERROR: 'DELETE_SUPERHERO_ERROR',

}

export default ACTION_TYPES;